name: Run Unit Tests

on:
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore DevPlanTracker.sln

    - name: Build Solution
      run: dotnet build DevPlanTracker.sln --no-restore

    - name: Run Tests
      run: dotnet test DevPlanTracker.sln --no-build --verbosity normal