name: Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag to deploy'
        required: false
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy-to-github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.version_tag || github.ref }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Publish the App
      run: dotnet publish DevPlanTracker/DevPlanTracker.csproj -c Release -o out --nologo

    - name: Configure for GitHub Pages
      run: |
        TARGET_DIR="out/wwwroot"
        
        # 1. Force creation of .nojekyll
        touch $TARGET_DIR/.nojekyll
        
        # 2. Fix Base Href for GitHub Pages routing
        sed -i 's|<base href="/"|<base href="/DevPlanTracker/"|g' $TARGET_DIR/index.html
        
        # 3. Create 404.html for direct URL navigation
        cp $TARGET_DIR/index.html $TARGET_DIR/404.html

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'out/wwwroot'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4