name: Create Release

on:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: patch

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Publish the App
      run: dotnet publish DevPlanTracker/DevPlanTracker.csproj -c Release -p:Version=${{ steps.tag_version.outputs.new_version }} -o release --nologo

    - name: Zip Artifacts
      run: |
        cd release/wwwroot
        zip -r ../../DevPlanTracker-${{ steps.tag_version.outputs.new_tag }}.zip .

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        files: DevPlanTracker-${{ steps.tag_version.outputs.new_tag }}.zip
        generate_release_notes: true